version: "3.4"

services:
  products:
    image:ruchinmunjal/microservicesapiproducts:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  orders:
    image:ruchinmunjal/microservicesapiorders:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  customers:
    image:ruchinmunjal/microservicesapicustomers:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  search:
    image:ruchinmunjal/microservicesapisearch:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://10.0.0.4:19081/lil/products/
      - Services__Orders=http://10.0.0.4:19081/lil/orders/
      - Services__Customers=http://10.0.0.4:19081/lil/customers/
    ports:
      - "6004:80"
